---
on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    uses: rwxd/gh-templates/.github/workflows/common-semantic-release.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
